spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://moonbuddy.cpyvecptwrde.eu-north-1.rds.amazonaws.com:3306/market?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: moonbuddy
    password: moonbuddy123!
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 621978938737-2dpk9sung4urrh0elrk7fir1c20grf5b.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email

cloud:
  aws:
    credentials:
      access-key: AKIA2N7UEW7JMRTGSVWO
      secret-key: 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
    s3:
      bucket: markeybucket
    stack:
      auto: false
    region:
      static: ap-northeast-2

jwt:
  secretKey: bWFya2V0SldUdG9rZW5zZWNyZXRrZXk=
  tokenExpired: 604800 #(sec) 7days